# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    docker:
      - image: ubuntu
    steps:
      - run: ln -s /usr/share/zoneinfo/America/Chicago /etc/localtime
      - run: apt update
      - run: apt install -y npm git reprepro gnupg
      - run: npm i -g cordova
      - checkout
      - run: ./update-version.sh
      - run: cordova platform add browser
      - run: cordova build browser --release
      - run: cordova platform add electron
      - run: rm -r node_modules/app-builder-bin && cp -a app-builder-bin node_modules
      - run: cordova build electron --release
      - run: git clone 'https://github.com/universe-software/telefy.git'
      - run: cd telefy && git branch www && git checkout www -- && git pull origin www
      - run: cp -r platforms/browser/www/. telefy
      - run: cd telefy && git add . && git commit -m "CircleCI Build \#$CIRCLE_BUILD_NUM"
      - run: cd telefy && git remote add github "https://$GIT_COMMITTER_NAME:$GITHUB_PASSWORD@github.com/universe-software/telefy.git" && git push github www
      - run: git clone 'https://github.com/universe-software/debian-repo.git'
      - run: reprepro -b debian-repo remove stable org.universe_software.telefy
      - run: wget "$PRIVATE_KEY_URL" -O universe-secret.gpg && gpg --import universe-secret.gpg && rm universe-secret.gpg
      - run: reprepro -b debian-repo includedeb stable platforms/electron/build/*.deb
      - run: cd debian-repo && git add . && git commit -m "Telefy CircleCI Build \#$CIRCLE_BUILD_NUM"
      - run: cd debian-repo && git remote add github "https://$GIT_COMMITTER_NAME:$GITHUB_PASSWORD@github.com/universe-software/debian-repo.git" && git push github master
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master